/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_name_token1 = 1,
  aux_sym_name_token2 = 2,
  aux_sym_program_keyword_token1 = 3,
  aux_sym_program_keyword_token2 = 4,
  aux_sym_program_keyword_token3 = 5,
  aux_sym_program_keyword_token4 = 6,
  aux_sym_program_keyword_token5 = 7,
  aux_sym_program_keyword_token6 = 8,
  aux_sym_integer_keyword_token1 = 9,
  aux_sym_integer_keyword_token2 = 10,
  aux_sym_integer_keyword_token3 = 11,
  aux_sym_integer_keyword_token4 = 12,
  aux_sym_double_colon_keyword_token1 = 13,
  aux_sym_end_keyword_token1 = 14,
  sym_comment = 15,
  sym_ampersand_newline = 16,
  sym_bare_ampersand = 17,
  anon_sym_SEMI = 18,
  sym__newline = 19,
  sym_source_file = 20,
  sym_program = 21,
  sym_program_stmt = 22,
  sym_end_program_stmt = 23,
  sym__specification_part_construct = 24,
  sym_variable_declaration = 25,
  sym_name = 26,
  sym_program_keyword = 27,
  sym_integer_keyword = 28,
  sym_double_colon_keyword = 29,
  sym_end_keyword = 30,
  sym_end_of_stmt = 31,
  sym__semicolon = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_program_repeat1 = 34,
  aux_sym_name_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_name_token1] = "name_token1",
  [aux_sym_name_token2] = "name_token2",
  [aux_sym_program_keyword_token1] = "program_keyword_token1",
  [aux_sym_program_keyword_token2] = "program_keyword_token2",
  [aux_sym_program_keyword_token3] = "program_keyword_token3",
  [aux_sym_program_keyword_token4] = "program_keyword_token4",
  [aux_sym_program_keyword_token5] = "program_keyword_token5",
  [aux_sym_program_keyword_token6] = "program_keyword_token6",
  [aux_sym_integer_keyword_token1] = "integer_keyword_token1",
  [aux_sym_integer_keyword_token2] = "integer_keyword_token2",
  [aux_sym_integer_keyword_token3] = "integer_keyword_token3",
  [aux_sym_integer_keyword_token4] = "integer_keyword_token4",
  [aux_sym_double_colon_keyword_token1] = "double_colon_keyword_token1",
  [aux_sym_end_keyword_token1] = "end_keyword_token1",
  [sym_comment] = "comment",
  [sym_ampersand_newline] = "ampersand_newline",
  [sym_bare_ampersand] = "bare_ampersand",
  [anon_sym_SEMI] = ";",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_program] = "program",
  [sym_program_stmt] = "program_stmt",
  [sym_end_program_stmt] = "end_program_stmt",
  [sym__specification_part_construct] = "_specification_part_construct",
  [sym_variable_declaration] = "variable_declaration",
  [sym_name] = "name",
  [sym_program_keyword] = "program_keyword",
  [sym_integer_keyword] = "integer_keyword",
  [sym_double_colon_keyword] = "double_colon_keyword",
  [sym_end_keyword] = "end_keyword",
  [sym_end_of_stmt] = "end_of_stmt",
  [sym__semicolon] = "_semicolon",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_name_repeat1] = "name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_name_token1] = aux_sym_name_token1,
  [aux_sym_name_token2] = aux_sym_name_token2,
  [aux_sym_program_keyword_token1] = aux_sym_program_keyword_token1,
  [aux_sym_program_keyword_token2] = aux_sym_program_keyword_token2,
  [aux_sym_program_keyword_token3] = aux_sym_program_keyword_token3,
  [aux_sym_program_keyword_token4] = aux_sym_program_keyword_token4,
  [aux_sym_program_keyword_token5] = aux_sym_program_keyword_token5,
  [aux_sym_program_keyword_token6] = aux_sym_program_keyword_token6,
  [aux_sym_integer_keyword_token1] = aux_sym_integer_keyword_token1,
  [aux_sym_integer_keyword_token2] = aux_sym_integer_keyword_token2,
  [aux_sym_integer_keyword_token3] = aux_sym_integer_keyword_token3,
  [aux_sym_integer_keyword_token4] = aux_sym_integer_keyword_token4,
  [aux_sym_double_colon_keyword_token1] = aux_sym_double_colon_keyword_token1,
  [aux_sym_end_keyword_token1] = aux_sym_end_keyword_token1,
  [sym_comment] = sym_comment,
  [sym_ampersand_newline] = sym_ampersand_newline,
  [sym_bare_ampersand] = sym_bare_ampersand,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_program] = sym_program,
  [sym_program_stmt] = sym_program_stmt,
  [sym_end_program_stmt] = sym_end_program_stmt,
  [sym__specification_part_construct] = sym__specification_part_construct,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_name] = sym_name,
  [sym_program_keyword] = sym_program_keyword,
  [sym_integer_keyword] = sym_integer_keyword,
  [sym_double_colon_keyword] = sym_double_colon_keyword,
  [sym_end_keyword] = sym_end_keyword,
  [sym_end_of_stmt] = sym_end_of_stmt,
  [sym__semicolon] = sym__semicolon,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_name_repeat1] = aux_sym_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_keyword_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_keyword_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_keyword_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_keyword_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_colon_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_end_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_ampersand_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_ampersand] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_program_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_end_program_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__specification_part_construct] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_program_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_double_colon_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_end_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_end_of_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym__semicolon] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 21,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 22,
        '&', 24,
        ':', 20,
        ';', 25,
        'A', 8,
        'a', 8,
        'D', 8,
        'd', 8,
        'E', 8,
        'e', 8,
        'G', 8,
        'g', 8,
        'I', 8,
        'i', 8,
        'M', 8,
        'm', 8,
        'N', 8,
        'n', 8,
        'O', 8,
        'o', 8,
        'P', 8,
        'p', 8,
        'R', 8,
        'r', 8,
        'T', 8,
        't', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(23);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '&') ADVANCE(24);
      if (lookahead == ';') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '&') ADVANCE(24);
      if (lookahead == ';') ADVANCE(25);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '&') ADVANCE(24);
      if (lookahead == ';') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '&') ADVANCE(24);
      if (lookahead == ':') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '!', 22,
        '&', 24,
        'A', 14,
        'a', 14,
        'D', 21,
        'd', 21,
        'E', 19,
        'e', 19,
        'G', 13,
        'g', 13,
        'I', 16,
        'i', 16,
        'M', 15,
        'm', 15,
        'N', 17,
        'n', 17,
        'O', 12,
        'o', 12,
        'P', 10,
        'p', 10,
        'R', 11,
        'r', 11,
        'T', 18,
        't', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_name_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_name_token2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_program_keyword_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_program_keyword_token2);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_program_keyword_token3);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_program_keyword_token4);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_program_keyword_token5);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_program_keyword_token6);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_integer_keyword_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_integer_keyword_token2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_integer_keyword_token3);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_integer_keyword_token4);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_double_colon_keyword_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_end_keyword_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_ampersand_newline);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_bare_ampersand);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '&') ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '&') ADVANCE(24);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '&') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_name_token1] = ACTIONS(1),
    [aux_sym_name_token2] = ACTIONS(1),
    [aux_sym_program_keyword_token1] = ACTIONS(1),
    [aux_sym_program_keyword_token2] = ACTIONS(1),
    [aux_sym_program_keyword_token3] = ACTIONS(1),
    [aux_sym_program_keyword_token4] = ACTIONS(1),
    [aux_sym_program_keyword_token5] = ACTIONS(1),
    [aux_sym_program_keyword_token6] = ACTIONS(1),
    [aux_sym_integer_keyword_token1] = ACTIONS(1),
    [aux_sym_integer_keyword_token2] = ACTIONS(1),
    [aux_sym_integer_keyword_token3] = ACTIONS(1),
    [aux_sym_integer_keyword_token4] = ACTIONS(1),
    [aux_sym_double_colon_keyword_token1] = ACTIONS(1),
    [aux_sym_end_keyword_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_ampersand_newline] = ACTIONS(3),
    [sym_bare_ampersand] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(37),
    [sym_program] = STATE(4),
    [sym_program_stmt] = STATE(2),
    [sym_program_keyword] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [aux_sym_program_keyword_token1] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_ampersand_newline] = ACTIONS(3),
    [sym_bare_ampersand] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(11), 1,
      aux_sym_integer_keyword_token1,
    ACTIONS(13), 1,
      aux_sym_integer_keyword_token4,
    STATE(6), 1,
      sym_end_keyword,
    STATE(10), 1,
      sym_integer_keyword,
    STATE(30), 1,
      sym_end_program_stmt,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    STATE(3), 3,
      sym__specification_part_construct,
      sym_variable_declaration,
      aux_sym_program_repeat1,
  [28] = 8,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(11), 1,
      aux_sym_integer_keyword_token1,
    ACTIONS(13), 1,
      aux_sym_integer_keyword_token4,
    STATE(6), 1,
      sym_end_keyword,
    STATE(10), 1,
      sym_integer_keyword,
    STATE(22), 1,
      sym_end_program_stmt,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    STATE(9), 3,
      sym__specification_part_construct,
      sym_variable_declaration,
      aux_sym_program_repeat1,
  [56] = 7,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(9), 1,
      aux_sym_program_keyword_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_program_stmt,
    STATE(5), 1,
      sym_program_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    STATE(7), 2,
      sym_program,
      aux_sym_source_file_repeat1,
  [80] = 6,
    ACTIONS(17), 1,
      aux_sym_name_token1,
    STATE(12), 1,
      sym_name,
    STATE(21), 1,
      sym__semicolon,
    STATE(28), 1,
      sym_end_of_stmt,
    ACTIONS(19), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [102] = 6,
    ACTIONS(21), 1,
      aux_sym_program_keyword_token1,
    STATE(8), 1,
      sym_program_keyword,
    STATE(25), 1,
      sym_end_of_stmt,
    STATE(32), 1,
      sym__semicolon,
    ACTIONS(23), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [124] = 7,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym_program_keyword_token1,
    STATE(2), 1,
      sym_program_stmt,
    STATE(5), 1,
      sym_program_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    STATE(7), 2,
      sym_program,
      aux_sym_source_file_repeat1,
  [148] = 6,
    ACTIONS(17), 1,
      aux_sym_name_token1,
    STATE(16), 1,
      sym_name,
    STATE(29), 1,
      sym_end_of_stmt,
    STATE(32), 1,
      sym__semicolon,
    ACTIONS(23), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [170] = 6,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(30), 1,
      aux_sym_integer_keyword_token1,
    ACTIONS(33), 1,
      aux_sym_integer_keyword_token4,
    STATE(10), 1,
      sym_integer_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    STATE(9), 3,
      sym__specification_part_construct,
      sym_variable_declaration,
      aux_sym_program_repeat1,
  [192] = 6,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(35), 1,
      aux_sym_name_token1,
    ACTIONS(37), 1,
      aux_sym_double_colon_keyword_token1,
    STATE(14), 1,
      sym_name,
    STATE(24), 1,
      sym_double_colon_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [212] = 4,
    ACTIONS(39), 1,
      aux_sym_name_token2,
    STATE(13), 1,
      aux_sym_name_repeat1,
    ACTIONS(41), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [228] = 4,
    STATE(21), 1,
      sym__semicolon,
    STATE(23), 1,
      sym_end_of_stmt,
    ACTIONS(19), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [244] = 4,
    ACTIONS(43), 1,
      aux_sym_name_token2,
    STATE(17), 1,
      aux_sym_name_repeat1,
    ACTIONS(45), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [260] = 4,
    STATE(21), 1,
      sym__semicolon,
    STATE(26), 1,
      sym_end_of_stmt,
    ACTIONS(19), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [276] = 4,
    STATE(20), 1,
      sym_end_of_stmt,
    STATE(21), 1,
      sym__semicolon,
    ACTIONS(19), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [292] = 4,
    STATE(27), 1,
      sym_end_of_stmt,
    STATE(32), 1,
      sym__semicolon,
    ACTIONS(23), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [308] = 4,
    ACTIONS(47), 1,
      aux_sym_name_token2,
    STATE(17), 1,
      aux_sym_name_repeat1,
    ACTIONS(50), 2,
      anon_sym_SEMI,
      sym__newline,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
  [324] = 2,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
    ACTIONS(52), 3,
      aux_sym_program_keyword_token1,
      anon_sym_SEMI,
      sym__newline,
  [335] = 2,
    ACTIONS(5), 3,
      sym_comment,
      sym_ampersand_newline,
      sym_bare_ampersand,
    ACTIONS(54), 3,
      aux_sym_name_token1,
      anon_sym_SEMI,
      sym__newline,
  [346] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(56), 2,
      aux_sym_integer_keyword_token1,
      aux_sym_integer_keyword_token4,
  [358] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(58), 2,
      aux_sym_integer_keyword_token1,
      aux_sym_integer_keyword_token4,
  [370] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [382] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(62), 2,
      aux_sym_integer_keyword_token1,
      aux_sym_integer_keyword_token4,
  [394] = 4,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(35), 1,
      aux_sym_name_token1,
    STATE(15), 1,
      sym_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [408] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [420] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(66), 2,
      aux_sym_integer_keyword_token1,
      aux_sym_integer_keyword_token4,
  [432] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [444] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(70), 2,
      aux_sym_integer_keyword_token1,
      aux_sym_integer_keyword_token4,
  [456] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [468] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [480] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(76), 2,
      aux_sym_name_token1,
      aux_sym_double_colon_keyword_token1,
  [492] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      aux_sym_program_keyword_token1,
  [504] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(78), 1,
      aux_sym_program_keyword_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [515] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(80), 1,
      aux_sym_double_colon_keyword_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [526] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(82), 1,
      aux_sym_program_keyword_token3,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [537] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(84), 1,
      aux_sym_integer_keyword_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [548] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [559] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(88), 1,
      aux_sym_program_keyword_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [570] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(90), 1,
      aux_sym_integer_keyword_token4,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [581] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(92), 1,
      aux_sym_end_keyword_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [592] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(94), 1,
      aux_sym_name_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [603] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(96), 1,
      aux_sym_program_keyword_token5,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [614] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(98), 1,
      aux_sym_integer_keyword_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [625] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(100), 1,
      aux_sym_program_keyword_token4,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [636] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(102), 1,
      aux_sym_program_keyword_token4,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [647] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(104), 1,
      aux_sym_program_keyword_token6,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [658] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(106), 1,
      aux_sym_integer_keyword_token4,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [669] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(108), 1,
      aux_sym_integer_keyword_token3,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
  [680] = 3,
    ACTIONS(5), 1,
      sym_bare_ampersand,
    ACTIONS(110), 1,
      aux_sym_program_keyword_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_ampersand_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 124,
  [SMALL_STATE(8)] = 148,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 228,
  [SMALL_STATE(13)] = 244,
  [SMALL_STATE(14)] = 260,
  [SMALL_STATE(15)] = 276,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 308,
  [SMALL_STATE(18)] = 324,
  [SMALL_STATE(19)] = 335,
  [SMALL_STATE(20)] = 346,
  [SMALL_STATE(21)] = 358,
  [SMALL_STATE(22)] = 370,
  [SMALL_STATE(23)] = 382,
  [SMALL_STATE(24)] = 394,
  [SMALL_STATE(25)] = 408,
  [SMALL_STATE(26)] = 420,
  [SMALL_STATE(27)] = 432,
  [SMALL_STATE(28)] = 444,
  [SMALL_STATE(29)] = 456,
  [SMALL_STATE(30)] = 468,
  [SMALL_STATE(31)] = 480,
  [SMALL_STATE(32)] = 492,
  [SMALL_STATE(33)] = 504,
  [SMALL_STATE(34)] = 515,
  [SMALL_STATE(35)] = 526,
  [SMALL_STATE(36)] = 537,
  [SMALL_STATE(37)] = 548,
  [SMALL_STATE(38)] = 559,
  [SMALL_STATE(39)] = 570,
  [SMALL_STATE(40)] = 581,
  [SMALL_STATE(41)] = 592,
  [SMALL_STATE(42)] = 603,
  [SMALL_STATE(43)] = 614,
  [SMALL_STATE(44)] = 625,
  [SMALL_STATE(45)] = 636,
  [SMALL_STATE(46)] = 647,
  [SMALL_STATE(47)] = 658,
  [SMALL_STATE(48)] = 669,
  [SMALL_STATE(49)] = 680,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_keyword, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_program_keyword, 7, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_of_stmt, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_stmt, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_program_stmt, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_program_stmt, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_stmt, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_program_stmt, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_keyword, 7, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [86] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_colon_keyword, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fortran(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fortran",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
